export const buttonsRu = [
    {
        size: 'small',
        btnType: 'input',
        name: 'Ё',
        value: 'ё',
        code: 'Backquote',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '1',
        value: '1',
        code: 'Digit1',
        shiftName: '!',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '2',
        value: '2',
        code: 'Digit2',
        shiftName: '"',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '3',
        value: '3',
        code: 'Digit3',
        shiftName: '№',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '4',
        value: '4',
        code: 'Digit4',
        shiftName: ';',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '5',
        value: '5',
        code: 'Digit5',
        shiftName: '%',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '6',
        value: '6',
        code: 'Digit6',
        shiftName: ':',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '7',
        value: '7',
        code: 'Digit7',
        shiftName: '?',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '8',
        value: '8',
        code: 'Digit8',
        shiftName: '*',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '9',
        value: '9',
        code: 'Digit9',
        shiftName: '(',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '0',
        value: '0',
        code: 'Digit0',
        shiftName: ')',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '-',
        value: '-',
        code: 'Minus',
        shiftName: '_',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '=',
        value: '=',
        code: 'Equal',
        shiftName: '+',
    },
    {
        size: 'wide',
        btnType: 'service',
        name: 'BACKSPACE',
        action: 'backspace',
        code: 'Backspace',
    },
    {
        size: 'wide',
        btnType: 'service',
        name: 'Tab',
        action: 'tab',
        code: 'Tab',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Й',
        value: 'й',
        code: 'KeyQ',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Ц',
        value: 'ц',
        code: 'KeyW',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'У',
        value: 'у',
        code: 'KeyE',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'К',
        value: 'к',
        code: 'KeyR',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Е',
        value: 'е',
        code: 'KeyT',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Н',
        value: 'н',
        code: 'KeyY',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Г',
        value: 'г',
        code: 'KeyU',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Ш',
        value: 'ш',
        code: 'KeyI',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Щ',
        value: 'щ',
        code: 'KeyO',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'З',
        value: 'з',
        code: 'KeyP',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Х',
        value: 'х',
        code: 'BracketLeft',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Ъ',
        value: 'ъ',
        code: 'BracketRight',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '\\',
        value: '\\',
        code: 'Backslash',
        shiftName: '/',
    },
    {
        size: 'small',
        btnType: 'service',
        name: 'DEL',
        action: 'del',
        code: 'Delete',
    },
    {
        size: 'wide',
        btnType: 'service',
        name: 'CapsLock',
        action: 'capsLock',
        code: 'CapsLock',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Ф',
        value: 'ф',
        code: 'KeyA',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Ы',
        value: 'ы',
        code: 'KeyS',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'В',
        value: 'в',
        code: 'KeyD',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'А',
        value: 'а',
        code: 'KeyF',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'П',
        value: 'п',
        code: 'KeyG',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Р',
        value: 'р',
        code: 'KeyH',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'О',
        value: 'о',
        code: 'KeyJ',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Л',
        value: 'л',
        code: 'KeyK',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Д',
        value: 'д',
        code: 'KeyL',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Ж',
        value: 'ж',
        code: 'Semicolon',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Э',
        value: 'э',
        code: 'Quote',
    },
    {
        size: 'extrawide',
        btnType: 'service',
        name: 'Enter',
        action: 'enter',
        code: 'Enter',
    },
    {
        size: 'extrawide',
        btnType: 'service',
        name: 'Shift',
        action: 'shift',
        code: 'ShiftLeft',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Я',
        value: 'я',
        code: 'KeyZ',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Ч',
        value: 'ч',
        code: 'KeyX',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'С',
        value: 'с',
        code: 'KeyC',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'М',
        value: 'м',
        code: 'KeyV',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'И',
        value: 'и',
        code: 'KeyB',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Т',
        value: 'т',
        code: 'KeyN',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Ь',
        value: 'ь',
        code: 'KeyM',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Б',
        value: 'б',
        code: 'Comma',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Ю',
        value: 'ю',
        code: 'Period',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '.',
        value: '.',
        shiftName: ',',
        code: 'Slash',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '↑',
        value: '↑',
        code: 'ArrowUp',
    },
    {
        size: 'wide',
        btnType: 'service',
        name: 'Shift',
        action: 'shift',
        code: 'ShiftRight',
    },
    {
        size: 'small',
        btnType: 'service',
        name: 'Ctrl',
        action: 'ctrl',
        code: 'ControlLeft',
    },
    {
        size: 'small',
        btnType: 'service',
        name: 'Win',
        action: 'win',
        code: 'MetaLeft',
    },
    {
        size: 'small',
        btnType: 'service',
        name: 'Alt',
        action: 'alt',
        code: 'AltLeft',
    },
    {
        size: 'extrawide',
        btnType: 'input',
        name: '',
        value: ' ',
        code: 'Space',
    },
    {
        size: 'small',
        btnType: 'service',
        name: 'Alt',
        action: 'alt',
        code: 'AltRight',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '←',
        value: '←',
        code: 'ArrowLeft',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '↓',
        value: '↓',
        code: 'ArrowDown',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '→',
        value: '→',
        code: 'ArrowRight',
    },
    {
        size: 'small',
        btnType: 'service',
        name: 'Ctrl',
        action: 'ctrl',
        code: 'ControlRight',
    },
]
