export const buttonsEn = [
    {
        size: 'small',
        btnType: 'input',
        name: '`',
        value:'`',
        code: 'Backquote',
        shiftName: '~',
    },
    {
        size: 'small',
        btnType: 'input',
        name:'1',
        value: '1',
        code: 'Digit1',
        shiftName: '!',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '2',
        value: '2',
        code: 'Digit2',
        shiftName: '@',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '3',
        value: '3',
        code: 'Digit3',
        shiftName: '#',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '4',
        value: '4',
        code: 'Digit4',
        shiftName: '$',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '5',
        value: '5',
        code: 'Digit5',
        shiftName: '%',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '6',
        value: '6',
        code: 'Digit6',
        shiftName: '^',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '7',
        value: '7',
        code: 'Digit7',
        shiftName: '&',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '8',
        value: '8',
        code: 'Digit8',
        shiftName: '*',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '9',
        value: '9',
        code: 'Digit9',
        shiftName: '(',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '0',
        value:'0',
        code: 'Digit0',
        shiftName: ')',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '-',
        value: '-',
        code: 'Minus',
        shiftName: '_',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '=',
        value: '=',
        code: 'Equal',
        shiftName: '+',
    },
    {
        size: 'wide',
        btnType: 'service',
        name: 'BACKSPACE',
        action: 'backspace',
        code: 'Backspace',
    },
    {
        size: 'wide',
        btnType: 'service',
        name: 'Tab',
        action: 'tab',
        code: 'Tab',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Q',
        value: 'q',
        code: 'KeyQ',
    },
    {
        size: 'small',
        btnType: 'input',
        name:'W',
        value: 'w',
        code: 'KeyW',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'E',
        value: 'e',
        code: 'KeyE',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'R',
        value: 'r',
        code: 'KeyR',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'T',
        value: 't',
        code: 'KeyT',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Y',
        value: 'y',
        code: 'KeyY',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'U',
        value: 'u',
        code: 'KeyU',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'I',
        value: 'i',
        code: 'KeyI',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'O',
        value: 'o',
        code: 'KeyO',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'P',
        value: 'p',
        code: 'KeyP',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '[',
        value: '[',
        code: 'BracketLeft',
        shiftName: '{',
    },
    {
        size: 'small',
        btnType: 'input',
        name: ']',
        value: ']',
        code: 'BracketRight',
        shiftName: '}',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '\\',
        value: '\\',
        code: 'Backslash',
        shiftName: '|',
    },
    {
        size: 'small',
        btnType: 'service',
        name: 'DEL',
        action: 'del',
        code: 'Delete',
    },
    {
        size: 'wide',
        btnType: 'service',
        name: 'CapsLock',
        action: 'capsLock',
        code: 'CapsLock',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'A',
        value: 'a',
        code: 'KeyA',
    },
    {
        size: 'small',
        btnType: 'input',
        name:'S',
        value: 's',
        code: 'KeyS',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'D',
        value: 'd',
        code: 'KeyD',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'F',
        value: 'f',
        code: 'KeyF',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'G',
        value: 'g',
        code: 'KeyG',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'H',
        value: 'h',
        code: 'KeyH',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'J',
        value: 'j',
        code: 'KeyJ',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'K',
        value: 'k',
        code: 'KeyK',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'L',
        value: 'l',
        code: 'KeyL',
    },
    {
        size: 'small',
        btnType: 'input',
        name: ';',
        value: ';',
        shiftName: ':',
        code: 'Semicolon',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '\'',
        value: '\'',
        shiftName: '"',
        code: 'Quote',
    },
    {
        size: 'extrawide',
        btnType: 'service',
        name: 'Enter',
        action: 'enter',
        code: 'Enter',
    },
    {
        size: 'extrawide',
        btnType: 'service',
        name: 'Shift',
        action: 'shift',
        code: 'ShiftLeft',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'Z',
        value: 'z',
        code: 'KeyZ',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'X',
        value: 'x',
        code: 'KeyX',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'C',
        value: 'c',
        code: 'KeyC',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'V',
        value: 'v',
        code: 'KeyV',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'B',
        value: 'b',
        code: 'KeyB',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'N',
        value: 'n',
        code: 'KeyN',
    },
    {
        size: 'small',
        btnType: 'input',
        name: 'M',
        value: 'm',
        code: 'KeyM',
    },
    {
        size: 'small',
        btnType: 'input',
        name: ',',
        value: ',',
        shiftName: '<',
        code: 'Comma',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '.',
        value: '.',
        shiftName: '>',
        code: 'Period',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '/',
        value: '/',
        shiftName: '/',
        code: 'Slash',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '↑',
        value: '↑',
        code: 'ArrowUp',
    },
    {
        size: 'wide',
        btnType: 'service',
        name: 'Shift',
        action: 'shift',
        code: 'ShiftRight',
    },
    {
        size: 'small',
        btnType: 'service',
        name: 'Ctrl',
        action: 'ctrl',
        code: 'ControlLeft',
    },
    {
        size: 'small',
        btnType: 'service',
        name: 'Win',
        action: 'win',
        code: 'MetaLeft',
    },
    {
        size: 'small',
        btnType: 'service',
        name: 'Alt',
        action: 'alt',
        code: 'AltLeft',
    },
    {
        size: 'extrawide',
        btnType: 'input',
        name: '',
        value: ' ',
        code: 'Space',
    },
    {
        size: 'small',
        btnType: 'service',
        name: 'Alt',
        action: 'alt',
        code: 'AltRight',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '←',
        value: '←',
        code: 'ArrowLeft',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '↓',
        value: '↓',
        code: 'ArrowDown',
    },
    {
        size: 'small',
        btnType: 'input',
        name: '→',
        value: '→',
        code: 'ArrowRight',
    },
    {
        size: 'small',
        btnType: 'service',
        name: 'Ctrl',
        action: 'ctrl',
        code: 'ControlRight',
    },
]